### ISSUE TITLE
Build Error for Artix Linux 6.12.1-artix1-1_x86-64

### ISSUE THREAD

**Issue by Johayan** [lwfinger/rtw89-BT#31]
==> dkms install --no-depmod rtw89bt-dkms-git/5.15.0.r40.g101e29a -k 6.12.1-artix1-1

Error! Bad return status for module build on kernel: 6.12.1-artix1-1 (x86_64)
Consult /var/lib/dkms/rtw89bt-dkms-git/5.15.0.r40.g101e29a/build/make.log for more information.
==> WARNING: `dkms install --no-depmod rtw89bt-dkms-git/5.15.0.r40.g101e29a -k 6.12.1-artix1-1' exited 10

from the make.log

DKMS make.log for rtw89bt-dkms-git-5.15.0.r40.g101e29a for kernel 6.12.1-artix1-1 (x86_64)
Tue Nov 26 15:21:59 CST 2024
make: Entering directory '/usr/lib/modules/6.12.1-artix1-1/build'
  CC [M]  /var/lib/dkms/rtw89bt-dkms-git/5.15.0.r40.g101e29a/build/btusb.o
  CC [M]  /var/lib/dkms/rtw89bt-dkms-git/5.15.0.r40.g101e29a/build/btrtl.o
  CC [M]  /var/lib/dkms/rtw89bt-dkms-git/5.15.0.r40.g101e29a/build/btmtk.o
  CC [M]  /var/lib/dkms/rtw89bt-dkms-git/5.15.0.r40.g101e29a/build/btintel.o
/var/lib/dkms/rtw89bt-dkms-git/5.15.0.r40.g101e29a/build/btrtl.c:10:10: fatal error: asm/unaligned.h: No such file or directory
   10 | #include <asm/unaligned.h>
      |          ^~~~~~~~~~~~~~~~~
compilation terminated.
make[2]: *** [scripts/Makefile.build:229: /var/lib/dkms/rtw89bt-dkms-git/5.15.0.r40.g101e29a/build/btrtl.o] Error 1
make[2]: *** Waiting for unfinished jobs....
/var/lib/dkms/rtw89bt-dkms-git/5.15.0.r40.g101e29a/build/btintel.c:14:10: fatal error: asm/unaligned.h: No such file or directory
   14 | #include <asm/unaligned.h>
      |          ^~~~~~~~~~~~~~~~~
compilation terminated.
make[2]: *** [scripts/Makefile.build:229: /var/lib/dkms/rtw89bt-dkms-git/5.15.0.r40.g101e29a/build/btintel.o] Error 1
/var/lib/dkms/rtw89bt-dkms-git/5.15.0.r40.g101e29a/build/btusb.c:21:10: fatal error: asm/unaligned.h: No such file or directory
   21 | #include <asm/unaligned.h>
      |          ^~~~~~~~~~~~~~~~~
compilation terminated.
make[2]: *** [scripts/Makefile.build:229: /var/lib/dkms/rtw89bt-dkms-git/5.15.0.r40.g101e29a/build/btusb.o] Error 1
make[1]: *** [/usr/lib/modules/6.12.1-artix1-1/build/Makefile:1936: /var/lib/dkms/rtw89bt-dkms-git/5.15.0.r40.g101e29a/build] Error 2
make: *** [Makefile:224: __sub-make] Error 2
make: Leaving directory '/usr/lib/modules/6.12.1-artix1-1/build'

Build System info:

System:
  Host: quokka Kernel: 6.11.8-artix1-2 arch: x86_64 bits: 64
  Desktop: KDE Plasma v: 6.2.3 Distro: Artix Linux
Machine:
  Type: Desktop System: ASUS product: N/A v: N/A serial: <superuser required>
  Mobo: ASUSTeK model: TUF GAMING X570-PRO (WI-FI) v: Rev X.0x
    serial: <superuser required> UEFI: American Megatrends v: 5013
    date: 03/22/2024
CPU:
  Info: 16-core model: AMD Ryzen 9 5950X bits: 64 type: MT MCP cache:
    L2: 8 MiB
  Speed (MHz): avg: 4000 min/max: 550/5981 cores: 1: 4000 2: 4000 3: 4000
    4: 4000 5: 4000 6: 4000 7: 4000 8: 4000 9: 4000 10: 4000 11: 4000 12: 4000
    13: 4000 14: 4000 15: 4000 16: 4000 17: 4000 18: 4000 19: 4000 20: 4000
    21: 4000 22: 4000 23: 4000 24: 4000 25: 4000 26: 4000 27: 4000 28: 4000
    29: 4000 30: 4000 31: 4000 32: 4000
Graphics:
  Device-1: Advanced Micro Devices [AMD/ATI] Navi 22 [Radeon RX 6700/6700
    XT/6750 XT / 6800M/6850M XT] driver: amdgpu v: kernel
  Device-2: Logitech C922 Pro Stream Webcam driver: snd-usb-audio,uvcvideo
    type: USB
  Display: wayland server: X.org v: 1.21.1.14 with: Xwayland v: 24.1.4
    compositor: kwin_wayland driver: X: loaded: amdgpu
    unloaded: fbdev,modesetting,radeon failed: vesa dri: radeonsi gpu: amdgpu
    resolution: 1: 1920x1080 2: 1080x1920
  API: EGL v: 1.5 drivers: kms_swrast,radeonsi,swrast
    platforms: gbm,wayland,x11,surfaceless,device
  API: OpenGL v: 4.6 compat-v: 4.5 vendor: amd mesa v: 24.2.7-arch1.1
    renderer: AMD Radeon RX 6700 XT (radeonsi navi22 LLVM 18.1.8 DRM 3.59
    6.11.8-artix1-2)
  API: Vulkan v: 1.3.295 drivers: radv,llvmpipe surfaces: xcb,xlib,wayland
Audio:
  Device-1: Advanced Micro Devices [AMD/ATI] Navi 21/23 HDMI/DP Audio
    driver: snd_hda_intel
  Device-2: Advanced Micro Devices [AMD] Starship/Matisse HD Audio
    driver: snd_hda_intel
  Device-3: Logitech C922 Pro Stream Webcam driver: snd-usb-audio,uvcvideo
    type: USB
  API: ALSA v: k6.11.8-artix1-2 status: kernel-api
  Server-1: PulseAudio v: 17.0 status: active
Network:
  Device-1: Intel Wi-Fi 6 AX200 driver: iwlwifi
  IF: wlan0 state: up mac: 38:fc:98:eb:6b:cb
  Device-2: Intel Ethernet I225-V driver: igc
  IF: eth0 state: up speed: 2500 Mbps duplex: full mac: 04:42:1a:e7:72:ed
Bluetooth:
  Device-1: Intel AX200 Bluetooth driver: btusb type: USB
  Report: rfkill ID: hci0 state: up address: see --recommends
Drives:
  Local Storage: total: 2.32 TiB used: 1.03 TiB (44.5%)
  ID-1: /dev/nvme0n1 model: AGAMMIXS70B-2T-CS size: 1.86 TiB
  ID-2: /dev/nvme1n1 vendor: Samsung model: SSD 980 500GB size: 465.76 GiB
Partition:
  ID-1: / size: 441.14 GiB used: 28.13 GiB (6.4%) fs: ext4 dev: /dev/nvme1n1p3
  ID-2: /boot/efi size: 511 MiB used: 288 KiB (0.1%) fs: vfat
    dev: /dev/nvme1n1p2
  ID-3: /home size: 1.83 TiB used: 1 TiB (54.6%) fs: ext4
    dev: /dev/nvme0n1p1
Swap:
  ID-1: swap-1 type: partition size: 16 GiB used: 2.5 GiB (15.6%)
    dev: /dev/nvme1n1p1
Sensors:
  System Temperatures: cpu: 44.5 C mobo: 43.6 C gpu: amdgpu temp: 54.0 C
  Fan Speeds (rpm): N/A gpu: amdgpu fan: 0
Info:
  Memory: total: 64 GiB note: est. available: 62.7 GiB used: 5.63 GiB (9.0%)
  Processes: 593 Uptime: 3d 18h 11m Shell: Bash inxi: 3.3.36

**Comment by Johayan** [comment]
Whoops!  Had a mind dump and thought I'd accidentally posted this to the rtw89-dkms github. So I closed it as I realized I was in the right place after all.

**Comment by Johayan** [comment]
Same exact error occurs for the cachyos-bore build as well on the same hardware. My first hunch is that something changed in the 6.12 tree.

**Comment by marco-calautti** [comment]
I also have the issue when installing kernel 6.13.6 on Arch.

**Comment by TheBlackKoala** [comment]
Check this comment on aur:
https://aur.archlinux.org/packages/rtw89bt-dkms-git#comment-1021387
